name: Rbac
version: '${project.version}'
main: me.gotha.rbac.Rbac
api-version: 1.16
authors: [ Gotha ]
description: Role Based Access Control
depend: [Multiverse-Core]
commands:
  lobby:
    usage: /lobby
  feast:
    usage: /feast
  leave:
    usage: /leave
  create:
    usage: /create
